<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Commands\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\NeuralDamage.Domain\NeuralDamage.Domain.csproj" />
	  <ProjectReference Include="..\NeuralDamage.Infrastructure\NeuralDamage.Infrastructure.csproj" />
	</ItemGroup>

</Project>
