export * from './applicationConfiguration.service';
import { ApplicationConfigurationService } from './applicationConfiguration.service';
export * from './attachments.service';
import { AttachmentsService } from './attachments.service';
export * from './bots.service';
import { BotsService } from './bots.service';
export * from './chatActions.service';
import { ChatActionsService } from './chatActions.service';
export * from './chatBots.service';
import { ChatBotsService } from './chatBots.service';
export * from './chatMembers.service';
import { ChatMembersService } from './chatMembers.service';
export * from './chats.service';
import { ChatsService } from './chats.service';
export * from './internalDevOnly.service';
import { InternalDevOnlyService } from './internalDevOnly.service';
export * from './messages.service';
import { MessagesService } from './messages.service';
export * from './neuralDamageAPI.service';
import { NeuralDamageAPIService } from './neuralDamageAPI.service';
export * from './reactions.service';
import { ReactionsService } from './reactions.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [ApplicationConfigurationService, AttachmentsService, BotsService, ChatActionsService, ChatBotsService, ChatMembersService, ChatsService, InternalDevOnlyService, MessagesService, NeuralDamageAPIService, ReactionsService, UserService];
