export * from './app.service';
import { AppService } from './app.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './bots.service';
import { BotsService } from './bots.service';
export * from './chatActions.service';
import { ChatActionsService } from './chatActions.service';
export * from './chatMembers.service';
import { ChatMembersService } from './chatMembers.service';
export * from './chats.service';
import { ChatsService } from './chats.service';
export * from './internalDevOnly.service';
import { InternalDevOnlyService } from './internalDevOnly.service';
export * from './messages.service';
import { MessagesService } from './messages.service';
export * from './reactions.service';
import { ReactionsService } from './reactions.service';
export const APIS = [AppService, AuthService, BotsService, ChatActionsService, ChatMembersService, ChatsService, InternalDevOnlyService, MessagesService, ReactionsService];
