/**
 * NeuralDamage.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttachmentDto { 
    id: string;
    url: string;
    contentType: string;
    sizeBytes: number;
    width?: number | null;
    height?: number | null;
    description?: string | null;
}

