/**
 * NeuralDamage.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BotCreatorDto } from './botCreatorDto';


export interface BotDto { 
    id: string;
    name: string;
    modelId: string;
    systemPrompt: string;
    personality?: string | null;
    temperature: number;
    avatarUrl?: string | null;
    aliases?: string | null;
    createdById: string;
    isActive: boolean;
    createdAt: string;
    isPublic: boolean;
    chatId?: string | null;
    createdBy: BotCreatorDto;
    chatCount: number;
    repliesToday: number;
    repliesLast7Days: number;
    modelStatus: string;
    modelStatusReason?: string | null;
}

