/**
 * NeuralDamage.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BotSummaryDto { 
    id: string;
    name: string;
    avatarUrl?: string | null;
    isActive: boolean;
    modelId: string;
}

