/**
 * NeuralDamage.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BotSummaryDto } from './botSummaryDto';
import { UserDto } from './userDto';


export interface ChatMemberDto { 
    id: string;
    chatId: string;
    userId?: string | null;
    botId?: string | null;
    role: string;
    joinedAt: string;
    user?: UserDto;
    bot?: BotSummaryDto;
}

