/**
 * NeuralDamage.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateBotRequest { 
    name: string;
    modelId: string;
    systemPrompt: string;
    personality?: string | null;
    temperature: number;
    avatarUrl?: string | null;
    aliases?: string | null;
}

