/**
 * NeuralDamage.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateBotRequest { 
    name?: string | null;
    modelId?: string | null;
    systemPrompt?: string | null;
    personality?: string | null;
    temperature?: number;
    avatarUrl?: string | null;
    aliases?: string | null;
}

