/**
 * NeuralDamage.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BotSummaryDto } from './botSummaryDto';
import { UserDto } from './userDto';
import { ReactionGroupDto } from './reactionGroupDto';
import { ReplyInfoDto } from './replyInfoDto';


export interface MessageDto { 
    id: string;
    chatId: string;
    senderUserId?: string | null;
    senderBotId?: string | null;
    content: string;
    mentions?: Array<string> | null;
    replyToId?: string | null;
    createdAt: string;
    senderUser?: UserDto;
    senderBot?: BotSummaryDto;
    reactions: Array<ReactionGroupDto>;
    replyTo?: ReplyInfoDto;
}

