/**
 * NeuralDamage.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelPricing } from './modelPricing';


export interface OpenRouterModel { 
    id: string;
    name: string;
    contextLength?: number | null;
    pricing?: ModelPricing;
    provider: string;
    description?: string | null;
    capabilities: Array<string>;
    priceTier: number;
}

