/**
 * NeuralDamage.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReactionGroupDto { 
    emoji: string;
    count: number;
    userIds: Array<string>;
    botIds: Array<string>;
    names: Array<string>;
}

